In [1]:
import pandas as pd

df = pd.read_csv("D:\python_project\cafe_recomendation\data\서울시 일반음식점 인허가 정보.csv", encoding="cp949")

C:\Users\inDBline\AppData\Local\Temp\ipykernel_9860\1479875966.py:3: DtypeWarning: Columns (0: 전화번호, 1: 도로명우편번호, 2: 건물소유구분명, 3: 전통업소지정번호, 4: 전통업소주된음식, 5: 홈페이지, 6: Unnamed: 40, 7: Unnamed: 42, 8: Unnamed: 43, 9: Unnamed: 44, 10: Unnamed: 46, 11: Unnamed: 47, 12: Unnamed: 49, 13: Unnamed: 50, 14: Unnamed: 51, 15: Unnamed: 52, 16: Unnamed: 53, 17: Unnamed: 54, 18: Unnamed: 57, 19: Unnamed: 60, 20: Unnamed: 61, 21: Unnamed: 62, 22: Unnamed: 70) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("D:\python_project\cafe_recomendation\data\서울시 일반음식점 인허가 정보.csv", encoding="cp949")

In [2]:
df = df[['사업장명', '상세영업상태명', '지번주소', '도로명주소','업태구분명']]

In [3]:
df = df[df['상세영업상태명'] != "폐업"]
df = df[df['업태구분명'] == "기타"]
df = df[df['지번주소'].str.contains('신림', na=False)]

In [4]:
df

,사업장명,상세영업상태명,지번주소,도로명주소,업태구분명
2002,서울대500동 나인온스버거,영업,서울특별시 관악구 신림동 산 56-1 서울대학교,"서울특별시 관악구 관악로 1, 서울대학교 500동 1층 A-105호 (신림동)",기타
33622,영차 티 컴퍼니(Young Cha Tea Company),영업,서울특별시 관악구 신림동 1445-19,"서울특별시 관악구 봉천로 196, 1층 3호 (신림동)",기타
33778,어반커피,영업,서울특별시 관악구 신림동 1638-26,서울특별시 관악구 신림로59길 11 (신림동),기타
34356,극야,영업,서울특별시 관악구 신림동 517-19,"서울특별시 관악구 신사로10길 8, 지하1층 1호 (신림동)",기타
35261,세이커리,영업,서울특별시 관악구 신림동 1655-17 G 밸리마인드,"서울특별시 관악구 시흥대로 558-1, 3층 301호 (신림동, G 밸리마인드)",기타
...,...,...,...,...,...
454857,꽃이다,영업,서울특별시 관악구 신림동 486-15,"서울특별시 관악구 관천로11길 76, 1층 (신림동)",기타
454888,슬로우 스푼,영업,서울특별시 관악구 신림동 1534-5,"서울특별시 관악구 대학6길 52, 1층 (신림동)",기타
454890,터틀랙 커피(Turtle Lack Coffee),영업,서울특별시 관악구 신림동 1423-3,"서울특별시 관악구 남부순환로181길 41, 1층 101호 (신림동)",기타
454891,삼모볼링센터휴게실,영업,서울특별시 관악구 신림동 1638-32 삼모스포렉스,"서울특별시 관악구 신림로59길 23, 삼모스포렉스 6층 (신림동)",기타
454893,퍼그피자하우스 신림점,영업,서울특별시 관악구 신림동 1431-12,"서울특별시 관악구 신림로 363, 지상 1~3층 (신림동)",기타

In [6]:
df1 = pd.read_csv("D:\python_project\cafe_recomendation\data\서울시 휴게음식점 인허가 정보.csv", encoding="cp949")

C:\Users\inDBline\AppData\Local\Temp\ipykernel_9860\1997164875.py:1: DtypeWarning: Columns (0: 건물소유구분명, 1: 전통업소지정번호, 2: 전통업소주된음식) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv("D:\python_project\cafe_recomendation\data\서울시 휴게음식점 인허가 정보.csv", encoding="cp949")

In [11]:
df1 = df1[['사업장명', '상세영업상태명', '지번주소', '도로명주소','업태구분명']]
df1 = df1[df1['상세영업상태명'] != "폐업"]
df1 = df1[df1['지번주소'].str.contains('신림', na=False)]

In [14]:
df1['업태구분명'].unique()

<StringArray>
[     '편의점',      '커피숍', '기타 휴게음식점',   '일반조리판매',    '아이스크림',    '패스트푸드',
       '다방',     '전통찻집',      '유원지',      '떡카페',      '백화점']
Length: 11, dtype: str

In [17]:
df1[df1['업태구분명'] == "기타 휴게음식점"]

,사업장명,상세영업상태명,지번주소,도로명주소,업태구분명
5454,컴포즈커피 신림녹두점,영업,서울특별시 관악구 신림동 238-9,"서울특별시 관악구 신림로 85, 1층 (신림동)",기타 휴게음식점
18088,원플레이 신림점,영업,서울특별시 관악구 신림동 1640-13,"서울특별시 관악구 신림로 329, 4층 (신림동)",기타 휴게음식점
31312,타래퀸 신림점,영업,서울특별시 관악구 신림동 1639-6 선인타운,"서울특별시 관악구 관천로 44, 선인타운 1층 101호 (신림동)",기타 휴게음식점
46897,반찬을담다,영업,서울특별시 관악구 신림동 607-73,"서울특별시 관악구 난곡로 220, 1층 (신림동)",기타 휴게음식점
47351,베리코이,영업,서울특별시 관악구 신림동 535-2,"서울특별시 관악구 조원로17길 14, 1층 102호 (신림동)",기타 휴게음식점
...,...,...,...,...,...
140018,Cafe 912,영업,서울특별시 관악구 신림동 1592-7,"서울특별시 관악구 신원로3길 42, 101호 (신림동)",기타 휴게음식점
140058,Sand&Soup(샌드앤수프),영업,서울특별시 관악구 신림동 100-14,"서울특별시 관악구 복은길 46, 1층 (신림동)",기타 휴게음식점
140479,제로백pc난곡사거리점,영업,서울특별시 관악구 신림동 527-2 프레콘빌딩,"서울특별시 관악구 난곡로 316, 프레콘빌딩 지하1층 (신림동)",기타 휴게음식점
140720,GS25 신림영락점,영업,서울특별시 관악구 신림동 98-427 금성하이츠빌라,"서울특별시 관악구 복은길 128, 101호 (신림동, 금성하이츠빌라)",기타 휴게음식점
141662,디저트39 신림역점,영업,서울특별시 관악구 신림동 1638-15,"서울특별시 관악구 신원로 39, 1층 (신림동)",기타 휴게음식점

In [18]:
df1[df1['업태구분명'] == "커피숍"]

,사업장명,상세영업상태명,지번주소,도로명주소,업태구분명
5367,밀크힐 신림점,영업,서울특별시 관악구 신림동 520-19,"서울특별시 관악구 조원로 97, 내제나호 1층 최우측 두번째호 (신림동)",커피숍
5387,공차 신림점,영업,서울특별시 관악구 신림동 1640-44 신광빌딩,"서울특별시 관악구 신림로 323, 신광빌딩 1층 106호 (신림동)",커피숍
9145,슈크렘 타로카페,영업,서울특별시 관악구 신림동 465-26,"서울특별시 관악구 남부순환로 1545, 1층 102호 (신림동)",커피숍
25580,달콤한걸베이커리,영업,서울특별시 관악구 신림동 1587-6,"서울특별시 관악구 관천로 45-1, 1층 103호(A-10) (신림동)",커피숍
39031,글로우,영업,서울특별시 관악구 신림동 520-20,"서울특별시 관악구 조원로 95, 1층 (신림동)",커피숍
...,...,...,...,...,...
140441,더벤티 신림점,영업,서울특별시 관악구 신림동 1424-11,"서울특별시 관악구 신림로 356, 1층 1호 (신림동)",커피숍
140607,히포커피 신림점,영업,서울특별시 관악구 신림동 127-72,"서울특별시 관악구 신림로12길 25, 지1층 (신림동)",커피숍
140721,바나프레소 신림역점,영업,서울특별시 관악구 신림동 1433-44,"서울특별시 관악구 남부순환로 1605, 1층 (신림동)",커피숍
141214,스트릿캔 신림점,영업,서울특별시 관악구 신림동 1411-10,"서울특별시 관악구 남부순환로190길 6, 1층 우측 (신림동)",커피숍
141675,매머드 익스프레스 신림대학점,영업,서울특별시 관악구 신림동 1514-9,"서울특별시 관악구 호암로26길 1, 1층 (신림동)",커피숍